import type {
  Alert,
  Capture,
  Case,
  CaseDetail,
  EngineerMetrics,
  Flow,
  FlowDetail,
  Graph,
  Host,
  Job,
  ProtocolStats,
  TimelineEvent,
} from '../types/api'

/**
 * Deterministic fixtures mirroring the backend API shapes (types/api.ts).
 * Used by per-page characterization tests — behavior is asserted against
 * these, so the Phase-3 sweep must not change what renders.
 */

export const captureFixture = (over: Partial<Capture> = {}): Capture => ({
  id: 'cap1',
  filename: 'c2_beacon.pcap',
  stored_path: '/tmp/uploads/c2_beacon.pcap',
  source: 'upload',
  status: 'completed',
  start_time: 1700000000,
  end_time: 1700000360,
  first_packet_ts: 1700000000,
  last_packet_ts: 1700000120,
  packet_count: 128,
  analyzed_packet_count: 128,
  size_bytes: 45_120,
  analysis_progress: 100,
  parser_used: 'scapy',
  error: null,
  created_at: '2026-09-12T10:00:00Z',
  completed_at: '2026-09-12T10:01:00Z',
  summary: {
    protocol_counts: { DNS: 6, HTTP: 4, TLS: 2 },
    transport_counts: { TCP: 10, UDP: 6 },
    unique_source_ips: 2,
    unique_destination_ips: 3,
    host_count: 5,
    alert_summary: {
      total: 2,
      by_severity: { critical: 1, high: 1, medium: 0, low: 0, info: 0 },
      by_rule: { beaconing: 1, dns_tunneling: 1 },
      max_score: 92,
    },
    flow_summary: {
      flow_count: 8,
      tcp_flows: 6,
      udp_flows: 2,
      failed_flows: 1,
      reset_flows: 2,
      retransmitting_flows: 3,
      tcp_states: { established: 4, closed: 2 },
      direction_counts: { outbound: 5, inbound: 2, internal: 1 },
    },
    dns_summary: { transactions: 6, unique_domains: 4, nxdomain_count: 1 },
    http_summary: { transactions: 4 },
    tls_summary: { sessions: 2, unique_sni: 2 },
  },
  ...over,
})

export const jobFixture = (over: Partial<Job> = {}): Job => ({
  id: 'job1',
  capture_id: 'cap1',
  type: 'full_analysis',
  status: 'completed',
  progress: 100,
  stage: 'completed',
  message: null,
  created_at: '2026-09-12T10:00:00Z',
  started_at: '2026-09-12T10:00:01Z',
  finished_at: '2026-09-12T10:01:00Z',
  result: { packets: 128, parser: 'scapy', flows: 8 },
  ...over,
})

export const alertFixture = (over: Partial<Alert> = {}): Alert => ({
  id: 'alert1',
  capture_id: 'cap1',
  rule_name: 'beaconing',
  title: 'Beaconing: 192.168.1.42 → 185.234.72.19',
  severity: 'critical',
  score: 92,
  source_ip: '192.168.1.42',
  destination_ip: '185.234.72.19',
  destination_port: 443,
  reasons: [
    { reason: 'Regular intervals', detail: 'interval jitter 4.2%', weight: 40 },
    { reason: 'Consistent destination', detail: '18 connections to one host', weight: 30 },
  ],
  evidence: {
    intervals_s: [30.1, 30.0, 30.2, 30.1],
    connections: 18,
    jitter_ratio: 0.042,
  },
  related_flow_ids: ['flow1', 'flow2'],
  related_packet_refs: [1, 2, 3],
  explanation: 'Periodic outbound connections with low jitter indicate C2 beaconing.',
  acknowledged: false,
  tags: [],
  note: null,
  timestamp: 1700000030,
  created_at: '2026-09-12T10:00:30Z',
  ...over,
})

export const flowFixture = (over: Partial<Flow> = {}): Flow => ({
  id: 'flow1',
  capture_id: 'cap1',
  source_ip: '192.168.1.42',
  destination_ip: '185.234.72.19',
  source_port: 51000,
  destination_port: 443,
  transport_protocol: 'TCP',
  application_protocol: 'TLS',
  first_seen: 1700000000,
  last_seen: 1700000100,
  packets: 12,
  bytes: 8_192,
  packets_forward: 6,
  bytes_forward: 4_096,
  packets_reverse: 6,
  bytes_reverse: 4_096,
  duration: 100,
  direction: 'outbound',
  tcp_state: 'established',
  retransmissions: 0,
  resets: 0,
  syn_count: 1,
  syn_retransmissions: 0,
  failed: false,
  created_at: '2026-09-12T10:00:00Z',
  ...over,
})

export const flowDetailFixture = (over: Partial<FlowDetail> = {}): FlowDetail => ({
  ...flowFixture(),
  packet_evidence: [
    {
      timestamp: 1700000000,
      source_ip: '192.168.1.42',
      destination_ip: '185.234.72.19',
      protocol: 'TLS',
      transport: 'TCP',
      source_port: 51000,
      destination_port: 443,
      length: 512,
      flags: ['SYN', 'ACK'],
      metadata: { seq: 100 },
      packet_reference: 1,
    },
    {
      timestamp: 1700000001,
      source_ip: '185.234.72.19',
      destination_ip: '192.168.1.42',
      protocol: 'TLS',
      transport: 'TCP',
      source_port: 443,
      destination_port: 51000,
      length: 1_500,
      flags: ['SYN', 'ACK'],
      metadata: { seq: 200 },
      packet_reference: 2,
    },
  ],
  ...over,
})

export const hostFixture = (over: Partial<Host> = {}): Host => ({
  id: 'host1',
  capture_id: 'cap1',
  ip: '192.168.1.42',
  mac: 'aa:bb:cc:dd:ee:ff',
  hostname: 'workstation-42',
  is_internal: true,
  first_seen: 1700000000,
  last_seen: 1700000120,
  packets_sent: 80,
  packets_received: 48,
  bytes_sent: 40_000,
  bytes_received: 12_000,
  protocols: { DNS: 6, TLS: 2, HTTP: 4 },
  services: [{ port: 22, service: 'ssh', transport: 'TCP', packets: 2 }],
  contacted: [{ ip: '185.234.72.19', port: 443, app_protocol: 'TLS', packets: 18, bytes: 9_000 }],
  role: 'workstation',
  behavior_summary: {
    dominant_protocol: 'DNS',
    protocol_distribution: { DNS: 6, TLS: 2, HTTP: 4 },
    unique_peers: 3,
    services_exposed: 1,
    connections_initiated: 10,
  },
  ...over,
})

export const dnsPageFixture = {
  items: [
    {
      id: 'dns1',
      capture_id: 'cap1',
      transaction_id: 1,
      client_ip: '192.168.1.42',
      server_ip: '192.168.1.1',
      query_name: 'c2.evil.example',
      query_type: 'A',
      response_ips: ['185.234.72.19'],
      is_response: false,
      rcode: 0,
      latency: 0.012,
      timestamp: 1700000030,
      packet_ref: 1,
    },
    {
      id: 'dns2',
      capture_id: 'cap1',
      transaction_id: 2,
      client_ip: '192.168.1.42',
      server_ip: '192.168.1.1',
      query_name: 'missing.example',
      query_type: 'A',
      response_ips: [],
      is_response: true,
      rcode: 3,
      latency: 0.020,
      timestamp: 1700000060,
      packet_ref: 2,
    },
  ],
  total: 2,
  offset: 0,
  limit: 50,
}

export const httpPageFixture = {
  items: [
    {
      id: 'http1',
      capture_id: 'cap1',
      client_ip: '192.168.1.42',
      server_ip: '93.184.216.34',
      server_port: 80,
      method: 'GET',
      host: 'example.com',
      path: '/',
      user_agent: 'Mozilla/5.0',
      status_code: 200,
      request_len: 128,
      response_len: 1_250,
      timestamp: 1700000010,
      packet_ref: 3,
    },
  ],
  total: 1,
  offset: 0,
  limit: 50,
}

export const tlsPageFixture = {
  items: [
    {
      id: 'tls1',
      capture_id: 'cap1',
      client_ip: '192.168.1.42',
      server_ip: '185.234.72.19',
      server_port: 443,
      sni: 'c2.evil.example',
      version: 'TLS 1.3',
      bytes: 4_096,
      packets: 6,
      first_seen: 1700000005,
      last_seen: 1700000095,
    },
  ],
  total: 1,
  offset: 0,
  limit: 50,
}

export const protocolStatsFixture = (over: Partial<ProtocolStats> = {}): ProtocolStats => ({
  dns: {
    transactions: 2,
    unique_domains: 2,
    nxdomain_count: 1,
    nxdomain_rate: 0.5,
    avg_latency: 0.016,
    top_domains: [
      { value: 'c2.evil.example', count: 1 },
      { value: 'missing.example', count: 1 },
    ],
    nxdomain_domains: [{ value: 'missing.example', count: 1 }],
    longest_queries: ['a-very-long-encoded-label.c2.evil.example'],
  },
  http: {
    transactions: 1,
    status_codes: { '200': 1 },
    methods: { GET: 1 },
    top_hosts: [{ value: 'example.com', count: 1 }],
    user_agents: { 'Mozilla/5.0': 1 },
    total_request_bytes: 128,
    total_response_bytes: 1_250,
  },
  ...over,
})

export const timelinePageFixture = {
  items: [
    {
      id: 'ev1',
      capture_id: 'cap1',
      event_type: 'alert',
      label: 'Beaconing: 192.168.1.42 → 185.234.72.19',
      timestamp: 1700000030,
      source_ip: '192.168.1.42',
      destination_ip: '185.234.72.19',
      destination_port: 443,
      protocol: 'TLS',
      domain: 'c2.evil.example',
      severity: 'critical',
      detail: { score: 92, rule: 'beaconing' },
      related_flow_id: 'flow1',
      related_alert_id: 'alert1',
      packet_ref: 1,
    },
    {
      id: 'ev2',
      capture_id: 'cap1',
      event_type: 'dns',
      label: 'DNS query: c2.evil.example',
      timestamp: 1700000060,
      source_ip: '192.168.1.42',
      destination_ip: '192.168.1.1',
      destination_port: 53,
      protocol: 'DNS',
      domain: 'c2.evil.example',
      severity: null,
      detail: { query_name: 'c2.evil.example', rcode: 3 },
      related_flow_id: null,
      related_alert_id: null,
      packet_ref: 2,
    },
  ],
  total: 2,
  offset: 0,
  limit: 50,
}

export const timelineEventsFixture = timelinePageFixture.items as TimelineEvent[]

export const graphFixture = (over: Partial<Graph> = {}): Graph => ({
  nodes: [
    { data: { id: '192.168.1.42', label: '192.168.1.42', type: 'host', internal: true, role: 'workstation' } },
    { data: { id: '185.234.72.19', label: '185.234.72.19', type: 'host', internal: false } },
    { data: { id: 'c2.evil.example', label: 'c2.evil.example', type: 'domain' } },
    { data: { id: 'c2-port', label: '443', type: 'service', port: 443, service: 'https' } },
  ],
  edges: [
    { data: { id: 'e1', source: '192.168.1.42', target: '185.234.72.19', type: 'flow', packets: 18, bytes: 9_000 } },
    { data: { id: 'e2', source: '192.168.1.42', target: 'c2.evil.example', type: 'dns', count: 1 } },
    { data: { id: 'e3', source: 'c2.evil.example', target: '185.234.72.19', type: 'resolve', count: 1 } },
    { data: { id: 'e4', source: '185.234.72.19', target: 'c2-port', type: 'service', packets: 18 } },
  ],
  stats: { node_count: 4, edge_count: 4, host_count: 2, domain_count: 1, service_count: 1 },
  ...over,
})

export const caseFixture = (over: Partial<Case> = {}): Case => ({
  id: 'case1',
  name: 'C2 Investigation',
  description: 'Beaconing from workstation-42',
  capture_ids: ['cap1'],
  status: 'open',
  created_at: '2026-09-12T10:00:00Z',
  updated_at: '2026-09-12T10:05:00Z',
  ...over,
})

export const caseDetailFixture = (over: Partial<CaseDetail> = {}): CaseDetail => ({
  ...caseFixture(),
  captures: [captureFixture()],
  stats: {
    capture_count: 1,
    total_packets: 128,
    total_alerts: 2,
    alerts_by_severity: { critical: 1, high: 1 },
    incidents: [
      {
        source_ip: '192.168.1.42',
        rule_names: ['beaconing', 'dns_tunneling'],
        alert_count: 2,
        max_score: 92,
        severity: 'critical',
        title: '192.168.1.42 — C2 beaconing pattern',
        story: 'Workstation-42 showed periodic TLS connections to a known-bad host.',
      },
    ],
    first_event_ts: 1700000000,
    last_event_ts: 1700000120,
  },
  ...over,
})

export const engineerMetricsFixture = (over: Partial<EngineerMetrics> = {}): EngineerMetrics => ({
  capture_duration_s: 120,
  total_packets: 128,
  total_bytes: 45_120,
  avg_pps: 1.1,
  peak_pps: 8,
  avg_bandwidth_bps: 3_000,
  peak_bandwidth_bps: 12_000,
  protocol_distribution: { DNS: 6, HTTP: 4, TLS: 2 },
  transport_distribution: { TCP: 10, UDP: 6 },
  tcp: {
    flows: 6,
    retransmissions: 3,
    retransmission_ratio: 0.02,
    syn_retransmissions: 1,
    resets: 2,
    reset_ratio: 0.33,
    failed_flows: 1,
    failure_ratio: 0.17,
    one_way_flows: 1,
  },
  dns: { transactions: 2, avg_latency_ms: 16, max_latency_ms: 20, p95_latency_ms: 20, nxdomain_rate: 0.5 },
  top_talkers: [{ ip: '192.168.1.42', sent_bytes: 40_000, received_bytes: 12_000, packets: 128 }],
  max_packet_size: 1_500,
  mtu_boundary_packets: 12,
  timeseries: {
    pps: [
      { t: 0, pps: 1 },
      { t: 10, pps: 2 },
      { t: 20, pps: 8 },
    ],
    bandwidth: [
      { t: 0, bps: 1_000 },
      { t: 10, bps: 2_000 },
      { t: 20, bps: 12_000 },
    ],
  },
  issues: [
    { issue: 'TCP retransmissions', severity: 'medium', detail: '3 retransmissions across 2 flows' },
    { issue: 'DNS NXDOMAIN rate', severity: 'low', detail: '50% of queries returned NXDOMAIN' },
  ],
  health: 'warning',
  ...over,
})

export const liveStatusFixture = {
  status: 'running' as const,
  interface: 'lo',
  bpf: 'tcp',
  packet_count: 42,
  elapsed_seconds: 10,
  max_packets: 100,
  max_seconds: 60,
  error: null,
}
